version: "3"
services:
  app:
    build: .
    command:
      sh -c "alembic upgrade head &&
            python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
